# my global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'lxtx-project'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - 'alert.rules'
  # - "first.rules"
  # - "second.rules"

# alert
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  #- job_name: 'prometheus'
  - job_name: 'prom_node'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    # scrape_configs:

    static_configs:
         - targets:
           - localhost:9090
           #- cadvisor:8080
           - node-exporter:9100

#scrape_configs:
#    - job_name: 'cadvisor-nodejs'
#      scrape_interval: 5s
#      static_configs:
#           - targets:
#             - 121.41.101.200:8080
#           - cadvisor:8080

  - job_name: 'cadvisor-nodejs'
    static_configs:
    - targets: ['121.41.101.200:8080']

  - job_name: 'snsweb2-process'
    static_configs:
    - targets: ['121.41.101.200:9256']


  - job_name: 'snsmq1-process'
    static_configs:
    - targets: ['121.40.218.197:9256']
  - job_name: 'snsmq2-process'
    static_configs:
    - targets: ['121.41.103.40:9256']
  - job_name: 'snsmq3-process'
    static_configs:
    - targets: ['121.40.216.19:9256']
#scrape_configs:
  # 采集node exporter监控数据
#  - job_name: 'hello-mq1'
#    static_configs:
#      - targets: ['3.0.19.138:9100']
#  - job_name: 'node resources'
#    scrape_interval: 10s
#    static_configs:
#      - targets:
#        - 'node-exporter:9100'
#  - job_name: 'debiantest'
#    static_configs:
#    - targets: ['111.231.144.243:9100']

  - job_name: 'hello-java1'
    static_configs:
    - targets: ['18.140.58.106:9100']

  - job_name: 'hello-java2'
    static_configs:
    - targets: ['13.229.65.25:9100']

  - job_name: 'hello-java3'
    static_configs:
    - targets: ['3.1.84.19:9100']
  - job_name: 'hello-java4'
    static_configs:
    - targets: ['13.229.71.103:9100']
## 5  6 
  - job_name: 'hello-java5'
    static_configs:
    - targets: ['54.169.215.1:9100']

  - job_name: 'hello-java6'
    static_configs:
    - targets: ['3.0.91.224:9100']

  - job_name: 'hello-mq1'
    static_configs:
    - targets: ['3.0.19.138:9100']

  - job_name: 'hello-mq2'
    static_configs:
    - targets: ['18.136.104.152:9100']

  - job_name: 'hello-mq3'
    static_configs:
    - targets: ['52.221.196.140:9100']

  - job_name: 'hello-ng1'
    static_configs:
    - targets: ['18.139.174.22:9100']

  - job_name: 'hello-ng2'
    static_configs:
    - targets: ['13.250.34.57:9100']


  - job_name: 'hello-proxy-73'
    static_configs:
    - targets: ['78.141.217.73:9100']


  - job_name: 'hello-proxy-182'
    static_configs:
    - targets: ['140.82.34.182:9100']


  - job_name: 'hello-proxy-177'
    static_configs:
    - targets: ['45.32.151.177:9100']


  - job_name: 'sns-stage'
    static_configs:
    - targets: ['103.204.78.34:9100']

  - job_name: 'sns-es1'
    static_configs:
    - targets: ['121.41.103.113:9100']

  - job_name: 'sns-web1'
    static_configs:
    - targets: ['121.40.16.31:9100']

  - job_name: 'sns-web2'
    static_configs:
    - targets: ['121.41.101.200:9100']

  - job_name: 'sns-php1'
    static_configs:
    - targets: ['121.40.243.52:9100']

  - job_name: 'sns-php2'
    static_configs:
    - targets: ['121.41.102.111:9100']

  - job_name: 'sns-mq1'
    static_configs:
    - targets: ['121.40.218.197:9100']

  - job_name: 'sns-mq2'
    static_configs:
    - targets: ['121.41.103.40:9100']
  - job_name: 'sns-mq3'
    static_configs:
    - targets: ['121.40.216.19:9100']

##market

  #- job_name: 'dev-market'
  #  static_configs:
  #  - targets: ['10.3.10.139:9100']

  - job_name: 'market-java01'
    static_configs:
    - targets: ['10.3.10.141:9100']
  - job_name: 'market-java02'
    static_configs:
    - targets: ['10.3.10.142:9100']

  #- job_name: 'market-java03'
  # static_configs:
  # - targets: ['10.3.10.143:9100']

  - job_name: 'market-java04'
    static_configs:
    - targets: ['10.3.10.150:9100']
  - job_name: 'market-lvs01'
    static_configs:
    - targets: ['10.3.10.144:9100']
  - job_name: 'market-lvs02'
    static_configs:
    - targets: ['10.3.10.145:9100']

  - job_name: pushgateway
    static_configs:
      - targets: ['13.250.34.57:9091']
        labels:
          instance: pushgateway

#scrape_configs:
  - job_name: 'market_redis_cluster'
    static_configs:
      #- targets: ['192.168.11.125:9121']
  ## config for the multiple Redis targets that the exporter will scrape
  #  - job_name: 'redis_exporter_targets'
  #  static_configs:
      - targets:
        - redis://10.3.10.141:7000
        - redis://10.3.10.141:7001
        - redis://10.3.10.142:7002
        - redis://10.3.10.142:7003
        - redis://10.3.10.143:7004
        - redis://10.3.10.143:7005
    metrics_path: /scrape
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 10.3.10.142:9121

##scrape_configs:
#  - job_name: 'redis_cluster'
#    static_configs:
#      #- targets: ['192.168.11.125:9121']
#  ## config for the multiple Redis targets that the exporter will scrape
#  #  - job_name: 'redis_exporter_targets'
#  #  static_configs:
#      - targets:
#        - redis://3.0.19.138:7000
#        - redis://3.0.19.138:7001
#        - redis://18.136.104.152:7002
#        - redis://18.136.104.152:7003
#        - redis://52.221.196.140:7004
#        - redis://52.221.196.140:7005
#    metrics_path: /scrape
#    relabel_configs:
#      - source_labels: [__address__]
#        target_label: __param_target
#      - source_labels: [__param_target]
#        target_label: instance
#      - target_label: __address__
#        replacement: 3.0.19.138:9121
#
#scrape_configs:
#  - job_name: 'redis_exporter'
#static_configs:
      #- targets: ['192.168.11.125:9121']
      #- targets: ['<<REDIS-EXPORTER-HOSTNAME>>:9121']

#  - job_name: 'redis'
#    static_configs:
#      - targets: ['192.168.11.125:9121']
#        labels:
#         instance: 'redis_freebsd'


  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        #- https://www.cailu.net/sitemap/index.xml
        #- https://www.cailu.net
        - https://apisns.cailuw.com
        #- https://www.cailu.net/market
        #- https://wiki.linuxchina.net
        #- http://apistatistical.cailuw.com
        - https://hk.search.yahoo.com
        #- https://hk.search.yahoo.com
        #- https://pagertree.com
        #- https://prometheus.io
        labels:
          instance: user_status
          grop: 'web'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        #replacement: "localhost:9115"  # Blackbox exporter.
        replacement: "blackbox_exporter:9115"  # Blackbox exporter.
      - target_label: region
        replacement: "local"


  - job_name: 'blackbox http_post_2xx'
    metrics_path: /probe
    params:
      module: [http_post_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - https://market-api.cailuw.com/api/v1/market/coin/rank/thirty
        #- https://linuxchina.net
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        #replacement: "localhost:9115"  # Blackbox exporter.
        #replacement: "10.3.10.124:9115"  # Blackbox exporter.
        replacement: "blackbox_exporter:9115"  # Blackbox exporter.
      - target_label: region
        replacement: "local"
